### ISSUE TITLE
sozlugun dumpı var mı?

### ISSUE THREAD

**Issue by csselo** [samedyildirim/tdk#1]
bi de curl ile post yapıorum sadece ascii olmalı diyor turkçe karakterlerde sonuç dönmüyor
ne yapmalıyım

**Comment by samedyildirim** [comment]
Merhabalar,

* Sözlüğün dump'ı yok, sozcuk tablosunu oluşturma cümleciği aşağıdaki gibi. 
* Sadece ascii olmalı gibi bir şeyi nerde gördünüz?
* Türkçe karakterlerde ne gibi bir problem yaşadınız?

Aşağıdaki bağlantıdan bu sayfanın örneğine ulaşabilirsiniz.
http://tdk.reddoc.net

İyi çalışmalar.

CREATE TABLE `sozcuk` (
  `sozcuk_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sozcuk` varchar(45) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `sozluk` varchar(45) CHARACTER SET utf8 NOT NULL,
  `sozcuk_anlami` text CHARACTER SET utf8,
  `eklenme_tarihi` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` varchar(45) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`sozcuk_id`)
) ENGINE=InnoDB AUTO_INCREMENT=227 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci

**Comment by csselo** [comment]
curl ile post ederken ascii olmalı yazıor

pycurl libde


İyi günler && Best regards

--
S.D. Selahaddin Yıldırım

**Comment by csselo** [comment]
http://pycurl.io/docs/latest/unicode.html

Only ASCII is accepted; ISO-8859-1/Latin 1, for example, will be rejected.

**Comment by samedyildirim** [comment]
Merhabalar,

1. Python ve PycURL kütüphanesi ile ilgili bir problem yaşıyor iseniz bunu php ile yazılmış bir projede sormak yerine ilgili kütüphane ile ilgili alanlarda danışmanız daha faydalı olacaktır.
2. Bağlantısını paylaştığınız dokümanı tekrar ve dikkatle okumanızı ve örnekleri incelemenizi tavsiye ediyorum.
3. "urlencode" anahtar kelimesi ile aramanıza devam etmeniz sizi sonuca daha hızlı ulaştıracaktır.

İyi çalışmalar.
